version: "3.3"

services:

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    links:
      - php

  php:
    build: ./php
    volumes:
      - ./:/var/www/html
    links:
      - db

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: webdatabase
    volumes:
      - ./db:/var/lib/mysql
